---
title: "Applied AI Bootcamp"
format: "html"
---

Welcome slides: [Introduction to Bootcamp](./W1/lessons/01_bootcamp_intro.qmd).

## Courses

- **Course 1: [Python](W1/)**
    Build strong Python programming foundations to apply and integrate ML/DL/AI in software systems.
- **Course 2: [Applied Data Science](W2/)**  
    Calculate, analyze, visualize, and interpret data. Then, formulate and test hypotheses.
- **Course 3: [Applied Machine Learning](W3/)**  
    Build reliable predictive modeling pipelines, debug its issues, evaluate and compare alternatives.
- **Course 4: [Agentic AI](W4/)**  
    Develop, debug, evaluate deploy, and monitor LLM-driven AI Agents to automate tasks involving unstructured data.
- **Course 5: [Applied Deep Learning](W5/)**  
    Use DL solution frameworks / libraries to apply AI to specific problems in NLP (language) and Computer Vision.
- **Course 6: Agentic Engineering**  
    Maximize the use of *Vibe Coding* via best practices to accelerate software development in your codebase.

**Estimated Duration**: 8 weeks.

## Sessions and Break times

- **Session 1**: 9:00 PM - 10:30 PM
- 15 minutes break
- **Session 2**: 10:45 PM - 12:00 PM
- Lunch break 12:00 - 1:00 PM
- **Session 3 (Labs and Exercises)**: 1:00 - 3:00 PM

## Classroom Communication

- Join the [Google Classroom](https://classroom.google.com/h) for:  
    announcements, deadlines, submission, quizzes, grades, ..etc.


## Proof-of-work via Git Commits (Mandatory)

It is required that you follow this instruction to get graded, for each exercise:

1. First, `git add` and `git commit` the exercise before solving it.
2. Each subsequent commit must have a full identifier such as:
    1. Course number (C1, C2, ...)
    2. Module number (M1, M2, ...)
    3. Exercise number (Ex1, Ex2, ...) -- i.e., a notebook
    4. Question number (Q1, Q2, ...) -- i.e., a step in the exercise of the notebook
3. Finally, `git push` before deadline
4. Mark it as done in Google Classroom (if assigned)

### Example

- **Execises**:
    - `C1 M2 Ex1: init` (1st exercise)
    - `C1 M2 Ex1: q1`   (question 1 solved)
    - `C1 M2 Ex1: q2`
    - `C1 M2 Ex2: init` (started 2nd exercise)
    - ...
- **Projects**:
    - `C1 Project: init`
    - `C1 Project: write analysis questions`
    - `C1 Project: explore the data`
    - ...
    - `C1 Project: add the 6th and 7th insight`

